//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAY1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADDRESS
    {
        public int PK_ADDRESS { get; set; }
        public Nullable<int> FK_CLIENT { get; set; }
        public string STREET { get; set; }
        public string HOUSE_NUMBER { get; set; }
        public string ROOM_NUMBER { get; set; }
        public Nullable<int> ENTRANCE_NUMBER { get; set; }
        public Nullable<int> FLOOR_NUMBER { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
    }
}
