//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAY1
{
    using System;
    using System.Collections.Generic;
    
    public partial class BASKET
    {
        public int PK_BASKET { get; set; }
        public Nullable<int> FK_PRODUCT { get; set; }
        public Nullable<int> FK_CLIENT { get; set; }
        public Nullable<int> COUNT { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
