//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAY1
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLOYEE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EMPLOYEE()
        {
            this.HISTORY = new HashSet<HISTORY>();
        }
    
        public int PK_EMPLOYEE { get; set; }
        public string SURNAME { get; set; }
        public string NAME { get; set; }
        public string SERIA_AND_NUMBER { get; set; }
        public string PATRONYMIC { get; set; }
        public string PHOTO { get; set; }
        public string NUMBER { get; set; }
        public string EMAIL { get; set; }
        public Nullable<int> FK_POST { get; set; }
        public string FK_LOGIN { get; set; }
        public Nullable<int> FK_SUBDVISION { get; set; }
    
        public virtual ACCESS_RIGHTS ACCESS_RIGHTS { get; set; }
        public virtual POST POST { get; set; }
        public virtual SUBDVISION SUBDVISION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HISTORY> HISTORY { get; set; }
    }
}
