//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAY1
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORY
    {
        public int PK_HISTORY { get; set; }
        public Nullable<int> FK_EMPLOYEE { get; set; }
        public Nullable<System.DateTime> DATE_TIME { get; set; }
    
        public virtual EMPLOYEE EMPLOYEE { get; set; }
    }
}
