//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAY1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Kabinet2Entities3 : DbContext
    {
        public Kabinet2Entities3()
            : base("name=Kabinet2Entities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACCESS_RIGHTS> ACCESS_RIGHTS { get; set; }
        public virtual DbSet<ADDRESS> ADDRESS { get; set; }
        public virtual DbSet<BASKET> BASKET { get; set; }
        public virtual DbSet<CATEGORY_PRODUCT> CATEGORY_PRODUCT { get; set; }
        public virtual DbSet<CLIENT> CLIENT { get; set; }
        public virtual DbSet<EMPLOYEE> EMPLOYEE { get; set; }
        public virtual DbSet<HISTORY> HISTORY { get; set; }
        public virtual DbSet<ORDERS> ORDERS { get; set; }
        public virtual DbSet<POST> POST { get; set; }
        public virtual DbSet<PRODUCT> PRODUCT { get; set; }
        public virtual DbSet<PRODUCT_IN_ORDER> PRODUCT_IN_ORDER { get; set; }
        public virtual DbSet<SUBDVISION> SUBDVISION { get; set; }
    }
}
