//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAY1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ORDERS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ORDERS()
        {
            this.PRODUCT_IN_ORDER = new HashSet<PRODUCT_IN_ORDER>();
        }
    
        public int PK_ORDERS { get; set; }
        public Nullable<System.DateTime> DATE_ORDER { get; set; }
        public Nullable<int> FK_CLIENT { get; set; }
        public Nullable<int> FINAL_PRICE { get; set; }
    
        public virtual CLIENT CLIENT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCT_IN_ORDER> PRODUCT_IN_ORDER { get; set; }
    }
}
