//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAY1
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT_IN_ORDER
    {
        public int PK_PRODUCT_IN_ORDER { get; set; }
        public Nullable<int> FK_ORDERS { get; set; }
        public Nullable<int> FK_PRODUCT { get; set; }
        public int COUNT { get; set; }
        public decimal PRICE_AT_PURCHASE { get; set; }
    
        public virtual ORDERS ORDERS { get; set; }
        public virtual PRODUCT PRODUCT { get; set; }
    }
}
